# Generated by Django 4.1 on 2022-12-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_posts_image_posts_user_alter_posts_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="headline",
            field=models.TextField(
                default="This is the headline",
                help_text="Brief Introduction",
                max_length=200,
            ),
        ),
    ]
