# Generated by Django 4.1 on 2022-12-05 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_posts_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 5, 10, 40, 25, 965140)
            ),
        ),
    ]
