# Generated by Django 4.1 on 2022-12-05 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_posts_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="full_story",
            field=models.TextField(
                default=models.TextField(
                    default="This is the headline", max_length=200
                ),
                max_length=1500,
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 5, 10, 43, 55, 697518)
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="headline",
            field=models.TextField(default="This is the headline", max_length=200),
        ),
    ]
